/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StatusRouteImport } from './routes/_status'
import { Route as StatusMainRouteImport } from './routes/_status/_main'
import { Route as StatusMainIndexRouteImport } from './routes/_status/_main/index'
import { Route as StatusSettingsLayoutRouteImport } from './routes/_status/settings/_layout'
import { Route as StatusMainAddRouteImport } from './routes/_status/_main/add'
import { Route as StatusSettingsLayoutPluginsInstallRouteImport } from './routes/_status/settings/_layout/plugins.install'

const StatusSettingsLayoutIndexLazyRouteImport = createFileRoute(
  '/_status/settings/_layout/',
)()
const StatusSettingsLayoutViewsLazyRouteImport = createFileRoute(
  '/_status/settings/_layout/views',
)()
const StatusSettingsLayoutMmdbLazyRouteImport = createFileRoute(
  '/_status/settings/_layout/mmdb',
)()
const StatusSettingsLayoutSessionsIndexLazyRouteImport = createFileRoute(
  '/_status/settings/_layout/sessions/',
)()
const StatusSettingsLayoutPresetsIndexLazyRouteImport = createFileRoute(
  '/_status/settings/_layout/presets/',
)()
const StatusSettingsLayoutPluginsIndexLazyRouteImport = createFileRoute(
  '/_status/settings/_layout/plugins/',
)()
const StatusSettingsLayoutSessionsAddLazyRouteImport = createFileRoute(
  '/_status/settings/_layout/sessions/add',
)()
const StatusSettingsLayoutSessionsIdLazyRouteImport = createFileRoute(
  '/_status/settings/_layout/sessions/$id',
)()
const StatusSettingsLayoutPresetsAddLazyRouteImport = createFileRoute(
  '/_status/settings/_layout/presets/add',
)()
const StatusSettingsLayoutPresetsIdLazyRouteImport = createFileRoute(
  '/_status/settings/_layout/presets/$id',
)()
const StatusSettingsLayoutPluginsAddLazyRouteImport = createFileRoute(
  '/_status/settings/_layout/plugins/add',
)()
const StatusSettingsLayoutPluginsIdLazyRouteImport = createFileRoute(
  '/_status/settings/_layout/plugins/$id',
)()

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/_status',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusMainRoute = StatusMainRouteImport.update({
  id: '/_main',
  getParentRoute: () => StatusRoute,
} as any)
const StatusMainIndexRoute = StatusMainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StatusMainRoute,
} as any)
const StatusSettingsLayoutRoute = StatusSettingsLayoutRouteImport.update({
  id: '/settings/_layout',
  path: '/settings',
  getParentRoute: () => StatusRoute,
} as any)
const StatusMainAddRoute = StatusMainAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => StatusMainRoute,
} as any)
const StatusSettingsLayoutIndexLazyRoute =
  StatusSettingsLayoutIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StatusSettingsLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_status/settings/_layout/index.lazy').then((d) => d.Route),
  )
const StatusSettingsLayoutViewsLazyRoute =
  StatusSettingsLayoutViewsLazyRouteImport.update({
    id: '/views',
    path: '/views',
    getParentRoute: () => StatusSettingsLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_status/settings/_layout/views.lazy').then((d) => d.Route),
  )
const StatusSettingsLayoutMmdbLazyRoute =
  StatusSettingsLayoutMmdbLazyRouteImport.update({
    id: '/mmdb',
    path: '/mmdb',
    getParentRoute: () => StatusSettingsLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_status/settings/_layout/mmdb.lazy').then((d) => d.Route),
  )
const StatusSettingsLayoutSessionsIndexLazyRoute =
  StatusSettingsLayoutSessionsIndexLazyRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => StatusSettingsLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_status/settings/_layout/sessions/index.lazy').then(
      (d) => d.Route,
    ),
  )
const StatusSettingsLayoutPresetsIndexLazyRoute =
  StatusSettingsLayoutPresetsIndexLazyRouteImport.update({
    id: '/presets/',
    path: '/presets/',
    getParentRoute: () => StatusSettingsLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_status/settings/_layout/presets/index.lazy').then(
      (d) => d.Route,
    ),
  )
const StatusSettingsLayoutPluginsIndexLazyRoute =
  StatusSettingsLayoutPluginsIndexLazyRouteImport.update({
    id: '/plugins/',
    path: '/plugins/',
    getParentRoute: () => StatusSettingsLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_status/settings/_layout/plugins/index.lazy').then(
      (d) => d.Route,
    ),
  )
const StatusSettingsLayoutSessionsAddLazyRoute =
  StatusSettingsLayoutSessionsAddLazyRouteImport.update({
    id: '/sessions/add',
    path: '/sessions/add',
    getParentRoute: () => StatusSettingsLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_status/settings/_layout/sessions/add.lazy').then(
      (d) => d.Route,
    ),
  )
const StatusSettingsLayoutSessionsIdLazyRoute =
  StatusSettingsLayoutSessionsIdLazyRouteImport.update({
    id: '/sessions/$id',
    path: '/sessions/$id',
    getParentRoute: () => StatusSettingsLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_status/settings/_layout/sessions/$id.lazy').then(
      (d) => d.Route,
    ),
  )
const StatusSettingsLayoutPresetsAddLazyRoute =
  StatusSettingsLayoutPresetsAddLazyRouteImport.update({
    id: '/presets/add',
    path: '/presets/add',
    getParentRoute: () => StatusSettingsLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_status/settings/_layout/presets/add.lazy').then(
      (d) => d.Route,
    ),
  )
const StatusSettingsLayoutPresetsIdLazyRoute =
  StatusSettingsLayoutPresetsIdLazyRouteImport.update({
    id: '/presets/$id',
    path: '/presets/$id',
    getParentRoute: () => StatusSettingsLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_status/settings/_layout/presets/$id.lazy').then(
      (d) => d.Route,
    ),
  )
const StatusSettingsLayoutPluginsAddLazyRoute =
  StatusSettingsLayoutPluginsAddLazyRouteImport.update({
    id: '/plugins/add',
    path: '/plugins/add',
    getParentRoute: () => StatusSettingsLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_status/settings/_layout/plugins/add.lazy').then(
      (d) => d.Route,
    ),
  )
const StatusSettingsLayoutPluginsIdLazyRoute =
  StatusSettingsLayoutPluginsIdLazyRouteImport.update({
    id: '/plugins/$id',
    path: '/plugins/$id',
    getParentRoute: () => StatusSettingsLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_status/settings/_layout/plugins/$id.lazy').then(
      (d) => d.Route,
    ),
  )
const StatusSettingsLayoutPluginsInstallRoute =
  StatusSettingsLayoutPluginsInstallRouteImport.update({
    id: '/plugins/install',
    path: '/plugins/install',
    getParentRoute: () => StatusSettingsLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof StatusMainIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/add': typeof StatusMainAddRoute
  '/settings': typeof StatusSettingsLayoutRouteWithChildren
  '/settings/mmdb': typeof StatusSettingsLayoutMmdbLazyRoute
  '/settings/views': typeof StatusSettingsLayoutViewsLazyRoute
  '/settings/': typeof StatusSettingsLayoutIndexLazyRoute
  '/settings/plugins/install': typeof StatusSettingsLayoutPluginsInstallRoute
  '/settings/plugins/$id': typeof StatusSettingsLayoutPluginsIdLazyRoute
  '/settings/plugins/add': typeof StatusSettingsLayoutPluginsAddLazyRoute
  '/settings/presets/$id': typeof StatusSettingsLayoutPresetsIdLazyRoute
  '/settings/presets/add': typeof StatusSettingsLayoutPresetsAddLazyRoute
  '/settings/sessions/$id': typeof StatusSettingsLayoutSessionsIdLazyRoute
  '/settings/sessions/add': typeof StatusSettingsLayoutSessionsAddLazyRoute
  '/settings/plugins/': typeof StatusSettingsLayoutPluginsIndexLazyRoute
  '/settings/presets/': typeof StatusSettingsLayoutPresetsIndexLazyRoute
  '/settings/sessions/': typeof StatusSettingsLayoutSessionsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof StatusMainIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/add': typeof StatusMainAddRoute
  '/settings/mmdb': typeof StatusSettingsLayoutMmdbLazyRoute
  '/settings/views': typeof StatusSettingsLayoutViewsLazyRoute
  '/settings': typeof StatusSettingsLayoutIndexLazyRoute
  '/settings/plugins/install': typeof StatusSettingsLayoutPluginsInstallRoute
  '/settings/plugins/$id': typeof StatusSettingsLayoutPluginsIdLazyRoute
  '/settings/plugins/add': typeof StatusSettingsLayoutPluginsAddLazyRoute
  '/settings/presets/$id': typeof StatusSettingsLayoutPresetsIdLazyRoute
  '/settings/presets/add': typeof StatusSettingsLayoutPresetsAddLazyRoute
  '/settings/sessions/$id': typeof StatusSettingsLayoutSessionsIdLazyRoute
  '/settings/sessions/add': typeof StatusSettingsLayoutSessionsAddLazyRoute
  '/settings/plugins': typeof StatusSettingsLayoutPluginsIndexLazyRoute
  '/settings/presets': typeof StatusSettingsLayoutPresetsIndexLazyRoute
  '/settings/sessions': typeof StatusSettingsLayoutSessionsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_status': typeof StatusRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_status/_main': typeof StatusMainRouteWithChildren
  '/_status/_main/add': typeof StatusMainAddRoute
  '/_status/settings/_layout': typeof StatusSettingsLayoutRouteWithChildren
  '/_status/_main/': typeof StatusMainIndexRoute
  '/_status/settings/_layout/mmdb': typeof StatusSettingsLayoutMmdbLazyRoute
  '/_status/settings/_layout/views': typeof StatusSettingsLayoutViewsLazyRoute
  '/_status/settings/_layout/': typeof StatusSettingsLayoutIndexLazyRoute
  '/_status/settings/_layout/plugins/install': typeof StatusSettingsLayoutPluginsInstallRoute
  '/_status/settings/_layout/plugins/$id': typeof StatusSettingsLayoutPluginsIdLazyRoute
  '/_status/settings/_layout/plugins/add': typeof StatusSettingsLayoutPluginsAddLazyRoute
  '/_status/settings/_layout/presets/$id': typeof StatusSettingsLayoutPresetsIdLazyRoute
  '/_status/settings/_layout/presets/add': typeof StatusSettingsLayoutPresetsAddLazyRoute
  '/_status/settings/_layout/sessions/$id': typeof StatusSettingsLayoutSessionsIdLazyRoute
  '/_status/settings/_layout/sessions/add': typeof StatusSettingsLayoutSessionsAddLazyRoute
  '/_status/settings/_layout/plugins/': typeof StatusSettingsLayoutPluginsIndexLazyRoute
  '/_status/settings/_layout/presets/': typeof StatusSettingsLayoutPresetsIndexLazyRoute
  '/_status/settings/_layout/sessions/': typeof StatusSettingsLayoutSessionsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/add'
    | '/settings'
    | '/settings/mmdb'
    | '/settings/views'
    | '/settings/'
    | '/settings/plugins/install'
    | '/settings/plugins/$id'
    | '/settings/plugins/add'
    | '/settings/presets/$id'
    | '/settings/presets/add'
    | '/settings/sessions/$id'
    | '/settings/sessions/add'
    | '/settings/plugins/'
    | '/settings/presets/'
    | '/settings/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/add'
    | '/settings/mmdb'
    | '/settings/views'
    | '/settings'
    | '/settings/plugins/install'
    | '/settings/plugins/$id'
    | '/settings/plugins/add'
    | '/settings/presets/$id'
    | '/settings/presets/add'
    | '/settings/sessions/$id'
    | '/settings/sessions/add'
    | '/settings/plugins'
    | '/settings/presets'
    | '/settings/sessions'
  id:
    | '__root__'
    | '/_status'
    | '/login'
    | '/setup'
    | '/_status/_main'
    | '/_status/_main/add'
    | '/_status/settings/_layout'
    | '/_status/_main/'
    | '/_status/settings/_layout/mmdb'
    | '/_status/settings/_layout/views'
    | '/_status/settings/_layout/'
    | '/_status/settings/_layout/plugins/install'
    | '/_status/settings/_layout/plugins/$id'
    | '/_status/settings/_layout/plugins/add'
    | '/_status/settings/_layout/presets/$id'
    | '/_status/settings/_layout/presets/add'
    | '/_status/settings/_layout/sessions/$id'
    | '/_status/settings/_layout/sessions/add'
    | '/_status/settings/_layout/plugins/'
    | '/_status/settings/_layout/presets/'
    | '/_status/settings/_layout/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StatusRoute: typeof StatusRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_status': {
      id: '/_status'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_status/_main': {
      id: '/_status/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StatusMainRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/_main/': {
      id: '/_status/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StatusMainIndexRouteImport
      parentRoute: typeof StatusMainRoute
    }
    '/_status/settings/_layout': {
      id: '/_status/settings/_layout'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof StatusSettingsLayoutRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/_main/add': {
      id: '/_status/_main/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof StatusMainAddRouteImport
      parentRoute: typeof StatusMainRoute
    }
    '/_status/settings/_layout/': {
      id: '/_status/settings/_layout/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof StatusSettingsLayoutIndexLazyRouteImport
      parentRoute: typeof StatusSettingsLayoutRoute
    }
    '/_status/settings/_layout/views': {
      id: '/_status/settings/_layout/views'
      path: '/views'
      fullPath: '/settings/views'
      preLoaderRoute: typeof StatusSettingsLayoutViewsLazyRouteImport
      parentRoute: typeof StatusSettingsLayoutRoute
    }
    '/_status/settings/_layout/mmdb': {
      id: '/_status/settings/_layout/mmdb'
      path: '/mmdb'
      fullPath: '/settings/mmdb'
      preLoaderRoute: typeof StatusSettingsLayoutMmdbLazyRouteImport
      parentRoute: typeof StatusSettingsLayoutRoute
    }
    '/_status/settings/_layout/sessions/': {
      id: '/_status/settings/_layout/sessions/'
      path: '/sessions'
      fullPath: '/settings/sessions/'
      preLoaderRoute: typeof StatusSettingsLayoutSessionsIndexLazyRouteImport
      parentRoute: typeof StatusSettingsLayoutRoute
    }
    '/_status/settings/_layout/presets/': {
      id: '/_status/settings/_layout/presets/'
      path: '/presets'
      fullPath: '/settings/presets/'
      preLoaderRoute: typeof StatusSettingsLayoutPresetsIndexLazyRouteImport
      parentRoute: typeof StatusSettingsLayoutRoute
    }
    '/_status/settings/_layout/plugins/': {
      id: '/_status/settings/_layout/plugins/'
      path: '/plugins'
      fullPath: '/settings/plugins/'
      preLoaderRoute: typeof StatusSettingsLayoutPluginsIndexLazyRouteImport
      parentRoute: typeof StatusSettingsLayoutRoute
    }
    '/_status/settings/_layout/sessions/add': {
      id: '/_status/settings/_layout/sessions/add'
      path: '/sessions/add'
      fullPath: '/settings/sessions/add'
      preLoaderRoute: typeof StatusSettingsLayoutSessionsAddLazyRouteImport
      parentRoute: typeof StatusSettingsLayoutRoute
    }
    '/_status/settings/_layout/sessions/$id': {
      id: '/_status/settings/_layout/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/settings/sessions/$id'
      preLoaderRoute: typeof StatusSettingsLayoutSessionsIdLazyRouteImport
      parentRoute: typeof StatusSettingsLayoutRoute
    }
    '/_status/settings/_layout/presets/add': {
      id: '/_status/settings/_layout/presets/add'
      path: '/presets/add'
      fullPath: '/settings/presets/add'
      preLoaderRoute: typeof StatusSettingsLayoutPresetsAddLazyRouteImport
      parentRoute: typeof StatusSettingsLayoutRoute
    }
    '/_status/settings/_layout/presets/$id': {
      id: '/_status/settings/_layout/presets/$id'
      path: '/presets/$id'
      fullPath: '/settings/presets/$id'
      preLoaderRoute: typeof StatusSettingsLayoutPresetsIdLazyRouteImport
      parentRoute: typeof StatusSettingsLayoutRoute
    }
    '/_status/settings/_layout/plugins/add': {
      id: '/_status/settings/_layout/plugins/add'
      path: '/plugins/add'
      fullPath: '/settings/plugins/add'
      preLoaderRoute: typeof StatusSettingsLayoutPluginsAddLazyRouteImport
      parentRoute: typeof StatusSettingsLayoutRoute
    }
    '/_status/settings/_layout/plugins/$id': {
      id: '/_status/settings/_layout/plugins/$id'
      path: '/plugins/$id'
      fullPath: '/settings/plugins/$id'
      preLoaderRoute: typeof StatusSettingsLayoutPluginsIdLazyRouteImport
      parentRoute: typeof StatusSettingsLayoutRoute
    }
    '/_status/settings/_layout/plugins/install': {
      id: '/_status/settings/_layout/plugins/install'
      path: '/plugins/install'
      fullPath: '/settings/plugins/install'
      preLoaderRoute: typeof StatusSettingsLayoutPluginsInstallRouteImport
      parentRoute: typeof StatusSettingsLayoutRoute
    }
  }
}

interface StatusMainRouteChildren {
  StatusMainAddRoute: typeof StatusMainAddRoute
  StatusMainIndexRoute: typeof StatusMainIndexRoute
}

const StatusMainRouteChildren: StatusMainRouteChildren = {
  StatusMainAddRoute: StatusMainAddRoute,
  StatusMainIndexRoute: StatusMainIndexRoute,
}

const StatusMainRouteWithChildren = StatusMainRoute._addFileChildren(
  StatusMainRouteChildren,
)

interface StatusSettingsLayoutRouteChildren {
  StatusSettingsLayoutMmdbLazyRoute: typeof StatusSettingsLayoutMmdbLazyRoute
  StatusSettingsLayoutViewsLazyRoute: typeof StatusSettingsLayoutViewsLazyRoute
  StatusSettingsLayoutIndexLazyRoute: typeof StatusSettingsLayoutIndexLazyRoute
  StatusSettingsLayoutPluginsInstallRoute: typeof StatusSettingsLayoutPluginsInstallRoute
  StatusSettingsLayoutPluginsIdLazyRoute: typeof StatusSettingsLayoutPluginsIdLazyRoute
  StatusSettingsLayoutPluginsAddLazyRoute: typeof StatusSettingsLayoutPluginsAddLazyRoute
  StatusSettingsLayoutPresetsIdLazyRoute: typeof StatusSettingsLayoutPresetsIdLazyRoute
  StatusSettingsLayoutPresetsAddLazyRoute: typeof StatusSettingsLayoutPresetsAddLazyRoute
  StatusSettingsLayoutSessionsIdLazyRoute: typeof StatusSettingsLayoutSessionsIdLazyRoute
  StatusSettingsLayoutSessionsAddLazyRoute: typeof StatusSettingsLayoutSessionsAddLazyRoute
  StatusSettingsLayoutPluginsIndexLazyRoute: typeof StatusSettingsLayoutPluginsIndexLazyRoute
  StatusSettingsLayoutPresetsIndexLazyRoute: typeof StatusSettingsLayoutPresetsIndexLazyRoute
  StatusSettingsLayoutSessionsIndexLazyRoute: typeof StatusSettingsLayoutSessionsIndexLazyRoute
}

const StatusSettingsLayoutRouteChildren: StatusSettingsLayoutRouteChildren = {
  StatusSettingsLayoutMmdbLazyRoute: StatusSettingsLayoutMmdbLazyRoute,
  StatusSettingsLayoutViewsLazyRoute: StatusSettingsLayoutViewsLazyRoute,
  StatusSettingsLayoutIndexLazyRoute: StatusSettingsLayoutIndexLazyRoute,
  StatusSettingsLayoutPluginsInstallRoute:
    StatusSettingsLayoutPluginsInstallRoute,
  StatusSettingsLayoutPluginsIdLazyRoute:
    StatusSettingsLayoutPluginsIdLazyRoute,
  StatusSettingsLayoutPluginsAddLazyRoute:
    StatusSettingsLayoutPluginsAddLazyRoute,
  StatusSettingsLayoutPresetsIdLazyRoute:
    StatusSettingsLayoutPresetsIdLazyRoute,
  StatusSettingsLayoutPresetsAddLazyRoute:
    StatusSettingsLayoutPresetsAddLazyRoute,
  StatusSettingsLayoutSessionsIdLazyRoute:
    StatusSettingsLayoutSessionsIdLazyRoute,
  StatusSettingsLayoutSessionsAddLazyRoute:
    StatusSettingsLayoutSessionsAddLazyRoute,
  StatusSettingsLayoutPluginsIndexLazyRoute:
    StatusSettingsLayoutPluginsIndexLazyRoute,
  StatusSettingsLayoutPresetsIndexLazyRoute:
    StatusSettingsLayoutPresetsIndexLazyRoute,
  StatusSettingsLayoutSessionsIndexLazyRoute:
    StatusSettingsLayoutSessionsIndexLazyRoute,
}

const StatusSettingsLayoutRouteWithChildren =
  StatusSettingsLayoutRoute._addFileChildren(StatusSettingsLayoutRouteChildren)

interface StatusRouteChildren {
  StatusMainRoute: typeof StatusMainRouteWithChildren
  StatusSettingsLayoutRoute: typeof StatusSettingsLayoutRouteWithChildren
}

const StatusRouteChildren: StatusRouteChildren = {
  StatusMainRoute: StatusMainRouteWithChildren,
  StatusSettingsLayoutRoute: StatusSettingsLayoutRouteWithChildren,
}

const StatusRouteWithChildren =
  StatusRoute._addFileChildren(StatusRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StatusRoute: StatusRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
