/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSettingsSessionsIdRouteImport } from './routes/_layout/settings.sessions.$id'
import { Route as LayoutSettingsPresetsIdRouteImport } from './routes/_layout/settings.presets.$id'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsSessionsIdRoute =
  LayoutSettingsSessionsIdRouteImport.update({
    id: '/sessions/$id',
    path: '/sessions/$id',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSettingsPresetsIdRoute = LayoutSettingsPresetsIdRouteImport.update({
  id: '/presets/$id',
  path: '/presets/$id',
  getParentRoute: () => LayoutSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/settings': typeof LayoutSettingsRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/settings/presets/$id': typeof LayoutSettingsPresetsIdRoute
  '/settings/sessions/$id': typeof LayoutSettingsSessionsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/settings': typeof LayoutSettingsRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/settings/presets/$id': typeof LayoutSettingsPresetsIdRoute
  '/settings/sessions/$id': typeof LayoutSettingsSessionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_layout/settings': typeof LayoutSettingsRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/settings/presets/$id': typeof LayoutSettingsPresetsIdRoute
  '/_layout/settings/sessions/$id': typeof LayoutSettingsSessionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/setup'
    | '/settings'
    | '/'
    | '/settings/presets/$id'
    | '/settings/sessions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/settings'
    | '/'
    | '/settings/presets/$id'
    | '/settings/sessions/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/setup'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/settings/presets/$id'
    | '/_layout/settings/sessions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/sessions/$id': {
      id: '/_layout/settings/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/settings/sessions/$id'
      preLoaderRoute: typeof LayoutSettingsSessionsIdRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/presets/$id': {
      id: '/_layout/settings/presets/$id'
      path: '/presets/$id'
      fullPath: '/settings/presets/$id'
      preLoaderRoute: typeof LayoutSettingsPresetsIdRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
  }
}

interface LayoutSettingsRouteChildren {
  LayoutSettingsPresetsIdRoute: typeof LayoutSettingsPresetsIdRoute
  LayoutSettingsSessionsIdRoute: typeof LayoutSettingsSessionsIdRoute
}

const LayoutSettingsRouteChildren: LayoutSettingsRouteChildren = {
  LayoutSettingsPresetsIdRoute: LayoutSettingsPresetsIdRoute,
  LayoutSettingsSessionsIdRoute: LayoutSettingsSessionsIdRoute,
}

const LayoutSettingsRouteWithChildren = LayoutSettingsRoute._addFileChildren(
  LayoutSettingsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutSettingsRoute: typeof LayoutSettingsRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSettingsRoute: LayoutSettingsRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
